spring.application.name=ParkWise

spring.datasource.url=jdbc:mysql://localhost:3306/parkwise
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=your-secret-key-change-this
jwt.expiration=8640000